name: icon
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - defaults
dependencies:
  - python=3.9
  - pytorch-cuda=11.8
  - torchvision
  - fvcore
  - iopath
  - nvidiacub
  - pyembree
  - pip
